services:
  golang-service:
    build:
      context: ./golang
      dockerfile: Dockerfile
    container_name: octo-jules-golang
    ports:
      - "8081:8080"
    restart: unless-stopped
    networks:
      - octo-jules-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  java-service:
    build:
      context: ./java
      dockerfile: Dockerfile
    container_name: octo-jules-java
    ports:
      - "8082:8080"
    restart: unless-stopped
    networks:
      - octo-jules-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  typescript-service:
    build:
      context: ./typescript
      dockerfile: Dockerfile
    container_name: octo-jules-typescript
    ports:
      - "8083:8080"
    restart: unless-stopped
    networks:
      - octo-jules-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  octo-jules-network:
    driver: bridge
